language: go
python:
  - "2.7"

sudo: required
install: "make install"
script:
- make ci
notifications:
  slack:
    secure: QwSscYSX1d60cEGhLN9T6CwN4tds8rFT5tpG6oWxv+OIL62wmk6i7PMtmV86VP1o2hX9VTqFqCfP4FgZEdHZKGLHo5FIhXXdaXqY4vHFQvfIrrbD6FB3b2R7YkNiu+PrQpK6cf4nzvNqXst0yEzGDOghIoIbgc13YL+aYGPSdMF+TkfnfFPD3B+WaMRVqb+G8+6s3bNKni6SP1GDGEIDi1NOFC7dzDzhWmvD1ysKMpPuBZGQ6HTgXXjT1TfLArjyHmsWcbLschRFM5Ies+4Ukw8At/szYdjXD7VWRN9EXKLFmqUnkkTVLN7VZGN+SxNm5iiSMqgx5jxxqpmQLqAxNAxd2pLWGg4urCI6JlHztXDA6rWPJqcbrLRW+K5DUHJUCMV7TxwVgaryVIrnFYRX/WGO4B4KDhk1QcBBjdcgM+YCpvsXaM3j+EdTOSnqTm11BmlOGSYZZk82Cb9TCdhCKC52HxWRBZeG2LJ9VeHCcW2eqeOXoK1pLCz6y52QEzxrgolgcHksl9tlmjhVYH5dGGL99NNcuHLM7b8Ep7h8va3IRIWgbAzYV4IPGpPuhjn63B829piBnn0Ci/OMhyi+bgsZcDUFqeesw5zwqw4hR7FKinsCSWYnlhFy8BVtwvKay6A0LSE76w20J3xqtNh49liNU+4k7/dljTiUojAH1q8=
